# Generated by Django 5.0.7 on 2024-09-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0006_alter_customuser_email_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=100)),
                ("context", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
