# Generated by Django 5.0.7 on 2024-09-08 07:57

from django.db import migrations, models

def set_global_id(apps, schema_editor):
    Conversation = apps.get_model('health_app', 'Conversation')
    db_alias = schema_editor.connection.alias
    conversations = Conversation.objects.using(db_alias).all().order_by('id')
    for index, conversation in enumerate(conversations, start=1):
        conversation.global_id = index
        conversation.save()

class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0007_conversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='global_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.RunPython(set_global_id),
        migrations.AlterField(
            model_name='conversation',
            name='global_id',
            field=models.IntegerField(unique=True),
        ),
    ]