# Generated by Django 5.0.7 on 2024-09-08 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0008_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="updated_at",
        ),
    ]
