# Generated by Django 5.0.7 on 2024-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0009_remove_conversation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="global_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
