# Generated by Django 5.0.7 on 2024-09-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0010_alter_conversation_global_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
