# Generated by Django 5.0.7 on 2024-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0011_customuser_age_customuser_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
