# Generated by Django 5.0.7 on 2024-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0013_medicalhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalhistory",
            name="height",
            field=models.FloatField(default=170.0),
        ),
        migrations.AddField(
            model_name="medicalhistory",
            name="weight",
            field=models.FloatField(default=70.0),
        ),
    ]
