# Generated by Django 5.0.7 on 2024-09-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0014_medicalhistory_height_medicalhistory_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalhistory",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="O+",
                max_length=3,
            ),
        ),
    ]
